export const WELCOME_PAGE  = '/'
export const LOGIN_PAGE    = '/login'
export const REGISTER_PAGE = '/register'
export const HOME_PAGE     = '/user/:id'
export const PROFILE_PAGE  = '/user/:id/profile'
export const PROJET_PAGE   = '/user/:id/linear/:project'
export const GANTT_PAGE    = '/user/:id/gantt/:project'
